name: "Build and Push"

on:
  push:
    tags:
      - '*'
    branches:
      - 'dev'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: lacework/lacework-docker-extension

    steps:
    - id: version
      uses: riege/action-version@v1

    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to Container Registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      with:
        image: tonistiigi/binfmt:latest
        platforms: arm64,arm
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and Push
      uses: docker/build-push-action@v3
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        build-args: |
          RELEASE=${{ steps.version.outputs.version }}
          HONEYCOMB_TEAM=${{ secrets.HONEYCOMB_TEAM }}
          HONEYCOMB_DATASET=${{ secrets.HONEYCOMB_DATASET }}
        tags: ${{ steps.meta.outputs.tags }}
